spring:
  application:
    name: Hunts

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/hunts
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml


  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: false
      lifecycle-management: start_only

logging:
  level:
    org:
      springframework:
        security: TRACE
server:
  port: 8081

# doc => https://medium.com/javarevisited/keycloak-integration-with-spring-security-6-37999f43ec85