spring:
  application:
    name: Hunts

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
#   url: ${DOCKER_DB_URL} for docker integration
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: false
      lifecycle-management: start_only

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 8081


# keycloak doc => https://medium.com/javarevisited/keycloak-integration-with-spring-security-6-37999f43ec85
