version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: samurai
      POSTGRES_USER: samurai
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/samurai  # Fixed database name to "samurai"
      KC_DB_USERNAME: samurai                            # Match database username
      KC_DB_PASSWORD: password                           # Match database password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8080:8080" # Keycloak HTTP
      - "8443:8443" # Keycloak HTTPS
    depends_on:
      - postgres
    command: start-dev --features=token-exchange

volumes:
  postgres_data:
